name: Validate Ansible Release

on:
  release:
    types: [created]

jobs:
  lint:
    name: Run ansible-lint on new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ansible and ansible-lint
        run: |
          pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint

  promote:
    name: Merge release branch into main
    needs: lint
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge release branch into main
        run: |
          git fetch origin main
          git checkout main
          git merge ${{ github.ref_name }} --no-ff -m "Merge release" --allow-unrelated-histories
          git push origin main
